language: julia
dist: xenial

env:
  - DYLD_FALLBACK_LIBRARY_PATH=""

os:
  - osx

julia:
  - 1.3
  - 1.4
  - nightly

branches:
  only:
    - master
    - /^release-.*/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
